on:
  push:
    branches:
    - main

jobs:
  joke:
    name: Tell me a joke
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Run joker.py
        run: python joker.py
        
